In [1]:
import numpy as np # For faster numerical calcualations

In [2]:
# array creation by numpy
arr =np.array([1,2,3,4,5])

In [3]:
print(type(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
1
(5,)


In [4]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [7]:
arr2 = np.array([[[1,2,3],
                 [4,5,6]]])

print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

<class 'numpy.ndarray'>
3
(1, 2, 3)


In [8]:
arr1*2 #showing numberical calcualtion working

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
#accessing #chain indexing
print(arr2[0][0][0])
print(arr[3])
print(arr1[1][0])

1
4
4


In [10]:
#acessing #multidimension indexing -faster
print(arr2[0 ,1, 1])
print(arr[4])
print(arr1[1,0])

5
5
4


In [11]:
#numpy uses concatination 
arr3 = np.array([[['a','n','c'],['p','b','d']],
        [['um','dm','cm'],['af','y','cf']]])
print(arr3.ndim)
print(arr3.shape)
word1 =arr3[0,0,1]+arr3[1,0,0]
word2 = arr3[0,1,0]+arr3[1,1,1]
word =word1 + word2
print(word)

3
(2, 2, 3)
numpy


In [12]:
#slicing #array[start :end:end] #row slicing
arr4 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9,],
                 [10,11,12]])
print(arr4.ndim)
print(arr4.shape)
print(arr4[0])
print(arr4[0:2])
print(arr4[::2])
print(arr4[::-1]) #reversing rows

2
(4, 3)
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [13]:
#column Slicing
print(arr4[:,0])
print(arr4[:,1:])
print(arr4[:,-1:])
print(arr4[:,:-1])
print(arr4[:,::-1])#reversing column
print(arr4[::-1,::-1])#reversing entirely

[ 1  4  7 10]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [14]:
#Scalar arithmetic operations
arr5 =np.array([1,2,3,4,5,7,8])
print(arr5 + 1)
print(arr5 - 1)
print(arr5 * 1)
print(arr5 / 1)
print(arr5 ** 5)

[2 3 4 5 6 8 9]
[0 1 2 3 4 6 7]
[1 2 3 4 5 7 8]
[1. 2. 3. 4. 5. 7. 8.]
[    1    32   243  1024  3125 16807 32768]


In [15]:
#vectoried arithmetic operation
#for applying funtions with out loops
print(np.sqrt(arr5))
arr6 = np.array([2.55,3.9,1.022])
print(np.round(arr6))
print(np.floor(arr6))#round down
print(np.ceil(arr6))#round up

[1.         1.41421356 1.73205081 2.         2.23606798 2.64575131
 2.82842712]
[3. 4. 1.]
[2. 3. 1.]
[3. 4. 2.]


In [16]:
#constants
print(np.pi)

3.141592653589793


In [17]:
#vectorised + Scalar operations

radii = np.array([3,6,9])

print("Area of circles :",np.pi *radii **2)

Area of circles : [ 28.27433388 113.09733553 254.46900494]


In [18]:
arr7 =np.array([9,4,5,7,8])
arr =np.array([1,2,3,4,5])

print(arr + arr7)
print(arr - arr7)
print(arr * arr7)
print(arr / arr7)
print(arr ** arr7)

[10  6  8 11 13]
[-8 -2 -2 -3 -3]
[ 9  8 15 28 40]
[0.11111111 0.5        0.6        0.57142857 0.625     ]
[     1     16    243  16384 390625]


In [19]:

print(arr == arr7)
arr7 = np.array([1,4,3,6,5])
print(arr == arr7)

[False False False False False]
[ True False  True False  True]


In [20]:
#comparison 
scores = np.array([91,100,55,40,73])

print(scores == 100)
print(scores >= 60)
print(scores < 60)
scores [scores < 60] = 0
print(scores)

[False  True False False False]
[ True  True False False  True]
[False False  True  True False]
[ 91 100   0   0  73]


In [21]:
#broadcasting is to allow to perform operations on array of different shapes
#condition : no.of col or row are match or either of them are 1. both row and column need from  follow backward
arr1 = arr1
arr8 = np.array([[1,4,7]])
print(arr1.shape)
print(arr8.shape)
print(arr1 *arr8)            


(2, 3)
(1, 3)
[[ 1  8 21]
 [ 4 20 42]]


In [22]:
#multiplication table by broadcasting

s = np.array([[1,2,3,4,5,6,7,8,9,10]])
c = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(s.shape)
print(c.shape)
print("multiplication array :",s * c)


(1, 10)
(10, 1)
multiplication array : [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [23]:
#aggregate function
# which summerize data and return mostly a single value
arr9 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
print(np.sum(arr9))
print(np.mean(arr9))
print(np.std(arr9))
print(np.var(arr9))
print(np.min(arr9), np.max(arr9))
print(np.argmin(arr9), np.argmax(arr9))
print(np.sum(arr9, axis = 0))#all columns sum
print(np.sum(arr9, axis = 1))#all row sum

55
5.5
2.8722813232690143
8.25
1 10
0 9
[ 7  9 11 13 15]
[15 40]


In [24]:
#flitering 
#process of  selecting elements that match the condition 
ages = np.array([[17,30,20,21,16,89,25],
                 [65,39,13,44,22,34,18]])

teenagers = ages[ages < 18]
adults = ages[(ages>=18) & (ages<65)]
Seniors = ages[ages>=65]
evens = ages[ages %2 == 0]
odds = ages[ages %2 != 0]
print(teenagers)# one d array
print(adults) #""
print(Seniors)#""
print(evens)#""
print(odds)


[17 16 13]
[30 20 21 25 39 44 22 34 18]
[89 65]
[30 20 16 44 22 34 18]
[17 21 89 25 65 39 13]


In [25]:
#WHERE : used to preserve the original shape
adults = np.where((ages>=18) & (ages<65) , ages ,-1)#where(x,y,fillvalues[any or 0 or np.nan or /])
print(adults)

[[-1 30 20 21 -1 -1 25]
 [-1 39 -1 44 22 34 18]]


In [26]:
#random numbers
rng = np.random.default_rng()
print(rng.integers(1,102 ,(5,3)))#low, high , size

[[75 46 15]
 [33 15 63]
 [81 58 99]
 [94 12 96]
 [72 12 45]]


In [27]:
rng = np.random.default_rng(seed = 1)# seed used to form same randam values , used to save same output
print(rng.integers(1,102 ,(5,3))) 

[[48 52 77]
 [96  4 15]
 [84 96 26]
 [32 88 43]
 [28 84 26]]


In [28]:
#for floating point
#uniform used to set range and gernerate random values between 0,1 by default
np.random.seed(seed =1)#setting the seed
print(np.random.uniform())#low, high,size

0.417022004702574


In [29]:
rng = np.random.default_rng()
array = np.array([1,4,5,6,8,9,10,2])
rng.shuffle(array)
print(array)

[10  9  4  6  1  8  5  2]


In [30]:
fruits = np.array(["apple","banana","coconut","orange"])
print(rng.choice(fruits,(3,3)))

[['apple' 'banana' 'orange']
 ['orange' 'apple' 'apple']
 ['apple' 'banana' 'orange']]
