In [ ]:
import numpy as np # For faster numerical calcualations

In [8]:
# array creation by numpy
arr =np.array([1,2,3,4,5])

In [25]:
print(type(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
1
(5,)


In [23]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [47]:
arr2 = np.array([[[1,2,3],
                 [4,5,6]]])

print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

<class 'numpy.ndarray'>
3
(1, 2, 3)


In [24]:
arr1*2 #showing numberical calcualtion working

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
#accessing #chain indexing
print(arr2[0][0][0])
print(arr[3])
print(arr1[1][0])

1
4
4


In [ ]:
#acessing #multidimension indexing -faster
print(arr2[0 ,1, 1])
print(arr[4])
print(arr1[1,0])

5
5
4


In [64]:
#numpy uses concatination 
arr3 = np.array([[['a','n','c'],['p','b','d']],
        [['um','dm','cm'],['af','y','cf']]])
print(arr3.ndim)
print(arr3.shape)
word1 =arr3[0,0,1]+arr3[1,0,0]
word2 = arr3[0,1,0]+arr3[1,1,1]
word =word1 + word2
print(word)

3
(2, 2, 3)
numpy


In [ ]:
#slicing #array[start :end:end] #row slicing
arr4 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9,],
                 [10,11,12]])
print(arr4.ndim)
print(arr4.shape)
print(arr4[0])
print(arr4[0:2])
print(arr4[::2])
print(arr4[::-1]) #reversing rows

2
(4, 3)
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [82]:
#column Slicing
print(arr4[:,0])
print(arr4[:,1:])
print(arr4[:,-1:])
print(arr4[:,:-1])
print(arr4[:,::-1])#reversing column
print(arr4[::-1,::-1])#reversing entirely

[ 1  4  7 10]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [83]:
#Scalar arithmetic operations
arr5 =np.array([1,2,3,4,5,7,8])
print(arr5 + 1)
print(arr5 - 1)
print(arr5 * 1)
print(arr5 / 1)
print(arr5 ** 5)

[2 3 4 5 6 8 9]
[0 1 2 3 4 6 7]
[1 2 3 4 5 7 8]
[1. 2. 3. 4. 5. 7. 8.]
[    1    32   243  1024  3125 16807 32768]


In [86]:
#vectoried arithmetic operation
#for applying funtions with out loops
print(np.sqrt(arr5))
arr6 = np.array([2.55,3.9,1.022])
print(np.round(arr6))
print(np.floor(arr6))#round down
print(np.ceil(arr6))#round up

[1.         1.41421356 1.73205081 2.         2.23606798 2.64575131
 2.82842712]
[3. 4. 1.]
[2. 3. 1.]
[3. 4. 2.]


In [88]:
#constants
print(np.pi)

3.141592653589793


In [ ]:
#vectorised + Scalar operations 
